name: Lint and test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run eslint
    - run: node salesforce-test.js
      env:
        TEST_CONSUMER_KEY: ${{ secrets.TEST_CONSUMER_KEY }}
        TEST_CONSUMER_SECRET: ${{ secrets.TEST_CONSUMER_SECRET }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
